### ISSUE TITLE
Fix Hostel Leave/Return Date

### ISSUE THREAD

**Issue by xAtishayx** [axios-iiitl/Hostel-Managment-Portal#34]
**Describe the bug**
Date should be beautified in Hostel Leave/Return Date

![image](https://user-images.githubusercontent.com/42544589/80258688-6de80400-86a1-11ea-8718-14cc58518864.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/42544589/80259399-1ea2d300-86a3-11ea-9889-841e006afe2e.png)

**Comment by blurry-x-face** [comment]
Hi @xAtishayx, we use `moment.js` for formatting date, it was accomplished in #33, would you be willing to help us out with this one, it'd be a great help, thanks!
